-- Questions
ALTER TABLE questions
ADD COLUMN language_id INT DEFAULT NULL,
ADD COLUMN input_format TEXT DEFAULT NULL,
ADD COLUMN output_format TEXT DEFAULT NULL,
ADD COLUMN sample_input TEXT DEFAULT NULL,
ADD COLUMN sample_output TEXT DEFAULT NULL,
ADD COLUMN default_code TEXT DEFAULT NULL,
ADD COLUMN solution_code TEXT DEFAULT NULL,
ADD COLUMN order_index INT DEFAULT 0,
ADD COLUMN created_by INT DEFAULT NULL,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Test Cases
ALTER TABLE test_cases
ADD COLUMN is_hidden TINYINT(1) DEFAULT 0;
